language: c
compiler:
  - gcc
# Change this to your needs
script:
  - ./autogen.sh
  - make
after_success:
  - make check | tee maketests.log
  - make distcheck | tee -a maketests.log
  - grep "Result: FAIL" maketests.log && exit 1
before_install:
  - sudo apt-get install autoconf
  - sudo apt-get install build-essential
  - sudo apt-get install gperf
  - sudo apt-get install check
