language: c
compiler:
  - gcc
# Change this to your needs
script:
  - ./autogen.sh
  - make
after_success:
  - make check || exit 1
  - make distcheck || exit 1
before_install:
  - sudo apt-get install autoconf
  - sudo apt-get install build-essential
  - sudo apt-get install gperf
  - sudo apt-get install check
notification:
  irc:
    channels:
      - "chat.freenode.net#naemon-devel"
    on_success: change
    on_failure: always
  email:
    - ozamosi@flukkost.nu
